# Generated by Django 3.2.7 on 2021-09-26 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tag_tag'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksDash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
