# Generated by Django 3.2.7 on 2021-09-28 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_tasksdash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TasksDash',
        ),
    ]
