# Generated by Django 3.2.7 on 2021-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='do_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
