# Generated by Django 3.2.7 on 2021-09-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20210922_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='do_date',
            field=models.DateField(null=True),
        ),
    ]
